# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_serverDialog(object):
    def setupUi(self, serverDialog):
        serverDialog.setObjectName("serverDialog")
        serverDialog.resize(379, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(serverDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serverHorizontalLayout = QtWidgets.QHBoxLayout()
        self.serverHorizontalLayout.setObjectName("serverHorizontalLayout")
        self.labelServerHost = QtWidgets.QLabel(serverDialog)
        self.labelServerHost.setObjectName("labelServerHost")
        self.serverHorizontalLayout.addWidget(self.labelServerHost)
        self.ServerHostlineEdit = QtWidgets.QLineEdit(serverDialog)
        self.ServerHostlineEdit.setObjectName("ServerHostlineEdit")
        self.serverHorizontalLayout.addWidget(self.ServerHostlineEdit)
        self.verticalLayout.addLayout(self.serverHorizontalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serverPortLabel = QtWidgets.QLabel(serverDialog)
        self.serverPortLabel.setObjectName("serverPortLabel")
        self.horizontalLayout.addWidget(self.serverPortLabel)
        self.ServerSpinBox = QtWidgets.QSpinBox(serverDialog)
        self.ServerSpinBox.setProperty("showGroupSeparator", True)
        self.ServerSpinBox.setMaximum(100000000)
        self.ServerSpinBox.setProperty("value", 5000)
        self.ServerSpinBox.setObjectName("ServerSpinBox")
        self.horizontalLayout.addWidget(self.ServerSpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.serverButtonBox = QtWidgets.QDialogButtonBox(serverDialog)
        self.serverButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.serverButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.serverButtonBox.setObjectName("serverButtonBox")
        self.verticalLayout.addWidget(self.serverButtonBox)

        self.retranslateUi(serverDialog)
        self.serverButtonBox.accepted.connect(serverDialog.accept) # type: ignore
        self.serverButtonBox.rejected.connect(serverDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(serverDialog)

    def retranslateUi(self, serverDialog):
        _translate = QtCore.QCoreApplication.translate
        serverDialog.setWindowTitle(_translate("serverDialog", "Dialog"))
        self.labelServerHost.setText(_translate("serverDialog", "Host"))
        self.ServerHostlineEdit.setText(_translate("serverDialog", "localhost"))
        self.serverPortLabel.setText(_translate("serverDialog", "Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    serverDialog = QtWidgets.QDialog()
    ui = Ui_serverDialog()
    ui.setupUi(serverDialog)
    serverDialog.show()
    sys.exit(app.exec_())
